language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sharktamer
  password:
    secure: LMVYkVon07ioWqz2CdyvBdviOk4dFQ1V/SNgrfDhRwhCXkP0gB1+XljCN3DamApp+YUvaVXwmQlxY8WwS1t8is4Py4TskDmRfKY9bDeFFuIQaHElMGvaQ5BSHEj/wWghWfqJJYMsXzWl/riOhEnez9BHV3vEzqWA/bFOEaJAt2otkcsBtXw1awTJYHAitctSLTs4eHzH6VEeg468IFqkK0C/MectBmVrGf3df5FFEzOZ336Oif1i4aN86+xPgXv5Bav+lG3Mk4AyKvEan8eQWG+QA0ekF5rRJpscFWOd1IfkBi7A3z0+RLXlC91WI1KyeC3QRmIgtfWn5RdZPgHOYSleM8hcy/xxrckcF4uBVXFsinAySOmWAb0yAEg5PplWEW3rdRk2Ki1jPjFPjHCTBm3H0F0H9kBKorHfdEH7fUOJ9tU8MzIVfa/iU9sBtJV0Qr3LgHc5ss2rTOiLnTPmJSAzKhSzjNWrgizxYONtoLVQqJ0isQzjsfROZeh4F6XAA28RCS3AAaqTuS/3N9X7opUjqnnPwbtGC+0YqLlxvtfv7lC7B3cu8nLuO4xc5/rnNH+E5EaB8/WVCfvFM+QvC8aQokmfh6RzDf5mlhrV7X6oV4sNLzezfdq0gNTaqpUOkunCR4gLs83bsSHUAIaL4lCSInI5+pnSeEIt7XTp9ps=
  on:
    tags: true
    repo: shanedabes/youtube_sm_parser
    python: 3.7
